name: KMEANS

channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.10
  - notebook=6.5.4
  - pyyaml=6.0
  - pip=23.0.1
  - numpy
  - pandas
  - pip:
    - langchain
    - openai
    - transformers
    - scikit-learn
    - torch
    - torchvision
    - scipy
    - python-dotenv
    - matplotlib
    - tiktoken
    - scipy
    - plotly
    - rich
    - streamlit
    - fuzzywuzzy
    - python-Levenshtein
    - seaborn